######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 16 23:24:01 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp
