######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 17 11:34:35 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
