######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 17 18:12:39 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
