######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 16 23:32:40 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
