######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 12 21:13:00 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp
